export const movieData = {
  status: "success",
  data: [
    {
      id: 1,
      title: "Inception",
      type: "Movie",
      genre: ["Sci-Fi", "Thriller"],
      release_year: 2010,
      rating: 8.8,
      description:
        "A thief who steals corporate secrets through dream-sharing technology is tasked with planting an idea.",
    },
    {
      id: 2,
      title: "Breaking Bad",
      type: "Web Show",
      genre: ["Crime", "Drama"],
      release_year: 2008,
      rating: 9.5,
      description:
        "A chemistry teacher turns to manufacturing drugs after a terminal diagnosis.",
    },
    {
      id: 3,
      title: "Interstellar",
      type: "Movie",
      genre: ["Sci-Fi", "Adventure"],
      release_year: 2014,
      rating: 8.6,
      description:
        "Explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    },
    {
      id: 4,
      title: "Stranger Things",
      type: "Web Show",
      genre: ["Sci-Fi", "Horror"],
      release_year: 2016,
      rating: 8.7,
      description:
        "A group of friends uncover supernatural mysteries in their small town.",
    },
    {
      id: 5,
      title: "The Dark Knight",
      type: "Movie",
      genre: ["Action", "Crime"],
      release_year: 2008,
      rating: 9.0,
      description:
        "Batman faces his greatest psychological and physical tests against the Joker.",
    },
    {
      id: 6,
      title: "Parasite",
      type: "Movie",
      genre: ["Drama", "Thriller"],
      release_year: 2019,
      rating: 8.6,
      description: "A poor family schemes to infiltrate a wealthy household.",
    },
    {
      id: 7,
      title: "The Mandalorian",
      type: "Web Show",
      genre: ["Action", "Adventure"],
      release_year: 2019,
      rating: 8.7,
      description:
        "A bounty hunter travels through the outer reaches of the galaxy.",
    },
    {
      id: 8,
      title: "Joker",
      type: "Movie",
      genre: ["Crime", "Drama"],
      release_year: 2019,
      rating: 8.4,
      description:
        "A troubled comedian spirals into madness and becomes the infamous Joker.",
    },
    {
      id: 9,
      title: "The Witcher",
      type: "Web Show",
      genre: ["Fantasy", "Adventure"],
      release_year: 2019,
      rating: 8.2,
      description:
        "A monster hunter struggles to find his place in a world where people can be more wicked than beasts.",
    },
    {
      id: 10,
      title: "The Crown",
      type: "Web Show",
      genre: ["Drama", "History"],
      release_year: 2016,
      rating: 8.6,
      description:
        "The political rivalries and romance of Queen Elizabeth II's reign.",
    },
    {
      id: 11,
      title: "Mad Max: Fury Road",
      type: "Movie",
      genre: ["Action", "Adventure"],
      release_year: 2015,
      rating: 8.1,
      description:
        "In a post-apocalyptic wasteland, Max helps a rebellious woman and a group of female prisoners.",
    },
    {
      id: 12,
      title: "Chernobyl",
      type: "Web Show",
      genre: ["Drama", "History"],
      release_year: 2019,
      rating: 9.4,
      description:
        "A dramatization of the 1986 nuclear disaster and its aftermath.",
    },
    {
      id: 13,
      title: "The Matrix",
      type: "Movie",
      genre: ["Sci-Fi", "Action"],
      release_year: 1999,
      rating: 8.7,
      description: "A hacker discovers the shocking truth about his reality.",
    },
    {
      id: 14,
      title: "Severance",
      type: "Web Show",
      genre: ["Sci-Fi", "Thriller"],
      release_year: 2022,
      rating: 8.6,
      description:
        "Employees undergo a procedure to separate their work and personal memories.",
    },
    {
      id: 15,
      title: "Fight Club",
      type: "Movie",
      genre: ["Drama", "Thriller"],
      release_year: 1999,
      rating: 8.8,
      description:
        "An insomniac office worker and a soap maker form an underground fight club.",
    },
    {
      id: 16,
      title: "The Boys",
      type: "Web Show",
      genre: ["Action", "Drama"],
      release_year: 2019,
      rating: 8.7,
      description:
        "A group of vigilantes set out to take down corrupt superheroes.",
    },
    {
      id: 17,
      title: "The Shawshank Redemption",
      type: "Movie",
      genre: ["Drama"],
      release_year: 1994,
      rating: 9.3,
      description:
        "Two imprisoned men bond over a number of years, finding solace and eventual redemption.",
    },
    {
      id: 18,
      title: "Black Mirror",
      type: "Web Show",
      genre: ["Sci-Fi", "Drama"],
      release_year: 2011,
      rating: 8.8,
      description:
        "Anthology series exploring a twisted, high-tech multiverse.",
    },
    {
      id: 19,
      title: "Whiplash",
      type: "Movie",
      genre: ["Drama", "Music"],
      release_year: 2014,
      rating: 8.5,
      description:
        "A promising young drummer is pushed to the limit by his instructor.",
    },
    {
      id: 20,
      title: "Narcos",
      type: "Web Show",
      genre: ["Crime", "Drama"],
      release_year: 2015,
      rating: 8.8,
      description:
        "The rise and fall of the most powerful drug lords in history.",
    },
    {
      id: 21,
      title: "The Godfather",
      type: "Movie",
      genre: ["Crime", "Drama"],
      release_year: 1972,
      rating: 9.2,
      description:
        "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
    },
    {
      id: 22,
      title: "Dark",
      type: "Web Show",
      genre: ["Sci-Fi", "Mystery"],
      release_year: 2017,
      rating: 8.7,
      description:
        "A family saga with a supernatural twist set in a German town.",
    },
    {
      id: 23,
      title: "Pulp Fiction",
      type: "Movie",
      genre: ["Crime", "Drama"],
      release_year: 1994,
      rating: 8.9,
      description:
        "The lives of two mob hitmen, a boxer, and others intertwine in tales of violence and redemption.",
    },
    {
      id: 24,
      title: "Succession",
      type: "Web Show",
      genre: ["Drama"],
      release_year: 2018,
      rating: 8.9,
      description: "The saga of a dysfunctional media family dynasty.",
    },
    {
      id: 25,
      title: "The Prestige",
      type: "Movie",
      genre: ["Drama", "Mystery"],
      release_year: 2006,
      rating: 8.5,
      description:
        "Two magicians become rivals in a deadly battle of one-upmanship.",
    },
    {
      id: 26,
      title: "The Last of Us",
      type: "Web Show",
      genre: ["Drama", "Adventure"],
      release_year: 2023,
      rating: 8.8,
      description:
        "A hardened survivor escorts a teenage girl across a post-apocalyptic US.",
    },
    {
      id: 27,
      title: "Gladiator",
      type: "Movie",
      genre: ["Action", "Drama"],
      release_year: 2000,
      rating: 8.5,
      description:
        "A former Roman General sets out to exact vengeance against the corrupt emperor.",
    },
    {
      id: 28,
      title: "Peaky Blinders",
      type: "Web Show",
      genre: ["Crime", "Drama"],
      release_year: 2013,
      rating: 8.8,
      description: "A gangster family epic set in 1900s England.",
    },
    {
      id: 29,
      title: "The Social Network",
      type: "Movie",
      genre: ["Drama", "Biography"],
      release_year: 2010,
      rating: 7.8,
      description: "The story of the founders of Facebook.",
    },
    {
      id: 30,
      title: "Money Heist",
      type: "Web Show",
      genre: ["Crime", "Thriller"],
      release_year: 2017,
      rating: 8.2,
      description: "A group of robbers carry out heists led by the Professor.",
    },
    {
      id: 31,
      title: "The Lord of the Rings: The Return of the King",
      type: "Movie",
      genre: ["Fantasy", "Adventure"],
      release_year: 2003,
      rating: 9.0,
      description:
        "The final confrontation between the forces of good and evil fighting for control of Middle-earth.",
    },
    {
      id: 32,
      title: "The Office (US)",
      type: "Web Show",
      genre: ["Comedy"],
      release_year: 2005,
      rating: 8.9,
      description: "A mockumentary on a group of typical office workers.",
    },
    {
      id: 33,
      title: "Her",
      type: "Movie",
      genre: ["Drama", "Romance"],
      release_year: 2013,
      rating: 8.0,
      description:
        "A lonely writer develops an unlikely relationship with an operating system.",
    },
    {
      id: 34,
      title: "The Expanse",
      type: "Web Show",
      genre: ["Sci-Fi", "Drama"],
      release_year: 2015,
      rating: 8.5,
      description:
        "A detective and a ship's crew unravel a vast conspiracy in a colonized solar system.",
    },
    {
      id: 35,
      title: "City of God",
      type: "Movie",
      genre: ["Crime", "Drama"],
      release_year: 2002,
      rating: 8.6,
      description:
        "The story of two boys growing up in a violent neighborhood of Rio de Janeiro.",
    },
    {
      id: 36,
      title: "Better Call Saul",
      type: "Web Show",
      genre: ["Crime", "Drama"],
      release_year: 2015,
      rating: 8.9,
      description:
        "The trials and tribulations of criminal lawyer Jimmy McGill.",
    },
    {
      id: 37,
      title: "Spirited Away",
      type: "Movie",
      genre: ["Animation", "Fantasy"],
      release_year: 2001,
      rating: 8.6,
      description:
        "A young girl enters the world of spirits and must find a way to free herself and her parents.",
    },
    {
      id: 38,
      title: "The Haunting of Hill House",
      type: "Web Show",
      genre: ["Horror", "Drama"],
      release_year: 2018,
      rating: 8.6,
      description:
        "Flashbacks reveal a family's horrifying experiences in a haunted mansion.",
    },
    {
      id: 39,
      title: "The Silence of the Lambs",
      type: "Movie",
      genre: ["Thriller", "Crime"],
      release_year: 1991,
      rating: 8.6,
      description:
        "A young FBI cadet seeks the help of an imprisoned cannibal to catch another serial killer.",
    },
    {
      id: 40,
      title: "The Handmaid's Tale",
      type: "Web Show",
      genre: ["Drama", "Sci-Fi"],
      release_year: 2017,
      rating: 8.4,
      description:
        "In a dystopian future, fertile women are forced into child-bearing slavery.",
    },
    {
      id: 41,
      title: "The Departed",
      type: "Movie",
      genre: ["Crime", "Thriller"],
      release_year: 2006,
      rating: 8.5,
      description:
        "An undercover cop and a mole in the police attempt to identify each other.",
    },
    {
      id: 42,
      title: "Sherlock",
      type: "Web Show",
      genre: ["Crime", "Drama"],
      release_year: 2010,
      rating: 9.1,
      description:
        "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
    },
    {
      id: 43,
      title: "The Lion King",
      type: "Movie",
      genre: ["Animation", "Adventure"],
      release_year: 1994,
      rating: 8.5,
      description:
        "Lion prince Simba and his father are targeted by his bitter uncle.",
    },
    {
      id: 44,
      title: "Arcane",
      type: "Web Show",
      genre: ["Animation", "Action"],
      release_year: 2021,
      rating: 9.0,
      description:
        "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war.",
    },
    {
      id: 45,
      title: "The Green Mile",
      type: "Movie",
      genre: ["Drama", "Fantasy"],
      release_year: 1999,
      rating: 8.6,
      description:
        "The lives of guards on Death Row are affected by one of their charges.",
    },
    {
      id: 46,
      title: "Mr. Robot",
      type: "Web Show",
      genre: ["Drama", "Thriller"],
      release_year: 2015,
      rating: 8.5,
      description:
        "A cybersecurity engineer and hacker suffers from social anxiety disorder and clinical depression.",
    },
    {
      id: 47,
      title: "The Pianist",
      type: "Movie",
      genre: ["Drama", "War"],
      release_year: 2002,
      rating: 8.5,
      description:
        "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto.",
    },
    {
      id: 48,
      title: "The Queen's Gambit",
      type: "Web Show",
      genre: ["Drama"],
      release_year: 2020,
      rating: 8.6,
      description:
        "Orphaned chess prodigy Beth Harmon struggles with addiction in a quest to become the greatest player.",
    },
    {
      id: 49,
      title: "Interrogation Room",
      type: "Movie",
      genre: ["Thriller", "Mystery"],
      release_year: 2018,
      rating: 7.4,
      description:
        "A detective races to uncover the truth in a high-stakes interrogation.",
    },
    {
      id: 50,
      title: "The Bear",
      type: "Web Show",
      genre: ["Drama"],
      release_year: 2022,
      rating: 8.5,
      description:
        "A young chef from the fine dining world comes home to run his family's sandwich shop.",
    },
  ],
};
